# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StockFetch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StockFetch
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  target 'StockFetchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StockFetchUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

