# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TryOutFirebase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TryOutFirebase

  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'FirebaseUI'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'

  target 'TryOutFirebaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TryOutFirebaseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
